title: Kairos Soteriology I
collections_dir: content
collections:
  week-01:
    output: true
  week-02:
    output: true
  week-03:
    output: true
  week-04:
    output: true
  week-05:
    output: true

